extends Node

enum Style {BASIC, CURLY, GIRL, SPIKEY, SHORT, MOP}
enum State {DEFAULT, FISHING, BUILDING, SHOP}
enum Tool {AXE, HOE, SWORD, WATER, FISH, SEED, HAMMER}
enum Machine {SPRINKLER, FISHER, SCARECROW, DELETE}
enum Seed {BEETROOT,CABBAGE, CARROT, CAULIFLOWER, KALE, PARSNIP, POTATO, PUMPKIN, RADISH, SUNFLOWER, WHEAT}
enum Item {WOOD, APPLE, TOMATO, CORN, WHEAT, PUMPKIN, FISH}
enum Shop {MAIN, HAT}
