extends Node

enum Style {BASIC, CURLY, GIRL, SPIKEY, SHORT, MOP}
enum State {DEFAULT, FISHING, BUILDING, SHOP}
enum Tool {AXE, HOE, SWORD, WATER, FISH, SEED, HAMMER}
enum Machine {SPRINKLER, FISHER, SCARECROW, DELETE}
enum Seed {BEETROOT,CABBAGE, CARROT, CAULIFLOWER, POTATO, PUMPKIN, RADISH, WHEAT}
enum Item {WOOD, BEETROOT, CABBAGE, CARROT, CAULIFLOWER, POTATO, PUMPKIN, RADISH, WHEAT, FISH, EGG}
enum Shop {MAIN, HAT}
